from django.db import migrations


CREATE_SQL = """
CREATE TABLE IF NOT EXISTS "fleet_vehicledocument" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "document_type" varchar(100) NOT NULL,
    "file" varchar(100) NOT NULL,
    "uploaded_at" timestamp with time zone NOT NULL,
    "vehicle_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "fleet_vehicledocument_vehicle_id_cb732d92"
    ON "fleet_vehicledocument" ("vehicle_id");
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fleet_vehicledocument_vehicle_id_cb732d92_fk_fleet_vehicle_id'
    ) THEN
        ALTER TABLE "fleet_vehicledocument" ADD CONSTRAINT
            "fleet_vehicledocument_vehicle_id_cb732d92_fk_fleet_vehicle_id"
            FOREIGN KEY ("vehicle_id") REFERENCES "fleet_vehicle" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""

REVERSE_SQL = """
ALTER TABLE "fleet_vehicledocument" DROP CONSTRAINT IF EXISTS
    "fleet_vehicledocument_vehicle_id_cb732d92_fk_fleet_vehicle_id";
DROP INDEX IF EXISTS "fleet_vehicledocument_vehicle_id_cb732d92";
DROP TABLE IF EXISTS "fleet_vehicledocument";
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auditlog_checkpoint_notification_vehiclelocation'),
    ]

    operations = [
        migrations.RunSQL(CREATE_SQL, REVERSE_SQL),
    ]
